### ISSUE TITLE
Request - Pam's Fruit Trees & Ars Nouveau

### ISSUE THREAD

**Issue by BriceFable** [Darkhax-Minecraft/BotanyTrees#10]
Hello hello! Politely requesting support for the trees added by these two mods.

https://www.curseforge.com/minecraft/mc-mods/ars-nouveau
https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-trees

**Comment by drakray** [comment]
Hi there, sorry GalloViking for hichhicking on your request :P

If I may suggest, adding support for Nether- and End- based tree, mainly from [OhTheBiomeYoullGo](https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go)?
Also [Fruit Trees](https://www.curseforge.com/minecraft/mc-mods/fruit-trees), [Vampirism](https://www.curseforge.com/minecraft/mc-mods/vampirism-become-a-vampire), and [Undergarden](https://www.curseforge.com/minecraft/mc-mods/the-undergarden)

Although, I might look into making it myself with the BotanyPots integrated CT Support now thaty I think about it lol

**Comment by Blackfenrir13** [comment]
> 
> 
> Hello hello! Politely requesting support for the trees added by these two mods.
> 
> https://www.curseforge.com/minecraft/mc-mods/ars-nouveau
> https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-trees

Yes is great mods and undergarden,fruit trees and vampirism too :D this mods need love ...or botanytrees :D @_@ plz lol

**Comment by Minothor** [comment]
Just chiming in here to say that I've submitted a PR for Pam's HC2 here: #12 

But it's really accessible, Galo, Drakay and BlackFenrir, the support is added via the datapack format - so if you added them you could either submit a PR to ask Darkhax to include them in the official mod or package the recipes up as a standalone datapack to add in the support locally.

(I've done that for my own server as a stop-gap measure - pack attached.)
[BotanyTrees_PHC.zip](https://github.com/Darkhax-Minecraft/BotanyTrees/files/5747874/BotanyTrees_PHC.zip)

**Comment by Darkhax** [comment]
Thanks for the help Minothor, your changes have now been included and [a new alpha](https://www.curseforge.com/minecraft/mc-mods/botany-trees/files/3151563) is already on CurseForge. I will be adding some of the other trees later on.

**Comment by Blackfenrir13** [comment]
Wow \o/ thx for the suport guys

**Comment by Minothor** [comment]
> Thanks for the help Minothor, your changes have now been included and [a new alpha](https://www.curseforge.com/minecraft/mc-mods/botany-trees/files/3151563) is already on CurseForge. I will be adding some of the other trees later on.

No worries, thanks for the really convenient recipe handling, I'm going to root around through the base botany pots to see how you implemented the recipe manager if that's ok?
Dropped out of modding for a few years and the forge rewrite has really thrown me for a loop!

**Comment by BriceFable** [comment]
Thanks everyone for all the work put into it! I'll try it out when I can. 

A few years back I would have done it myself (or attempted it, at least) but I'm new to 1.16, so I don't know a whole lot about the way the "new" forge works. And I know even less about Fabric.

**Comment by Minothor** [comment]
@GalloViking don't worry, same here - I was talking about the recipe handling on the back end. 

It means that adding support for other trees is as easy as adding a json file for each tree.

Take a look at the [silentgear nether tree](https://github.com/Darkhax-Minecraft/BotanyTrees/tree/1.16.4/src/main/resources/data/botanytrees/recipes/silentgear) as an example.

I took that as my starting point and template, replicating and tweaking it for all of the Pam's trees.

If you don't feel comfortable reading the other mod's source code to get the sapling/item ids, then you can try making a testing world locally and installing the CraftTweaker mod.
You can then see details and Ids by holding the item in your hand and typing:
```
/ct hand
```

Hope this helps!

**Comment by BriceFable** [comment]
@Minothor I use CT, I know a few of the useful commands. I have also made my own compatibility configs for a lot of mods back in 1.12.2 when I was using Bonsai Trees, but that seems even easier since I don't have to make the whole tree shape in the configs!

**Comment by ModernGamingWorld** [comment]
Added The Undergarden Soil/farmland support(https://github.com/Darkhax-Minecraft/BotanyPots/pull/122)

**Comment by ModernGamingWorld** [comment]
Added Undergarden Tree support(https://github.com/Darkhax-Minecraft/BotanyTrees/pull/14)

**Comment by Darkhax** [comment]
I believe that's all for this issue report. Thanks to everyone who helped add these trees.
