### ISSUE TITLE
Request: Support for Extended Nether Backport?

### ISSUE THREAD

**Issue by WordStormRose** [Darkhax-Minecraft/BotanyTrees#11]
Hello, 

Would you consider adding support for Extended Nether Backport (https://www.curseforge.com/minecraft/mc-mods/extended-nether-backport) to your 1.15 version of this mod or allowing new trees to be added in the config file?

Thank you, have a good holiday!

**Comment by Darkhax** [comment]
Hello, I am not pushing updates for 1.15 anymore however unofficial support can be adde using data packs or CraftTweaker.
