### ISSUE TITLE
Sugerence: Add Pam's trees compat

### ISSUE THREAD

**Issue by aburone** [Darkhax-Minecraft/BotanyTrees#17]
Pam's harvestcraft has several fruit trees. Having them in pots would be really nice.

**Comment by Water-Cat1** [comment]
Olive tree is typo'd as `olice` in the files
Also the maple tree isn't working as `pamhc2trees:mapleitem` should be `pamhc2trees:maplesyrupitem`

**Comment by Darkhax** [comment]
Pams trees should already be supported. Olive and maple are fixed in the next update.
