### ISSUE TITLE
Request for 1.16.1

### ISSUE THREAD

**Issue by Mingu2209** [Darkhax-Minecraft/BotanyTrees#2]
Hi,

Sorry if I leave the message in the incorrect place (I'm kinda new in Github). I'm in love with Botany pots mod and I would love if you could create botany trees for people playing in 1.16.1 that are already using your other mod.

Thanks a lot in advance and thanks for the effort you put on this mod!

**Comment by Darkhax** [comment]
The new update should work fine on 1.16.1 even though it says 1.16.3 in the file name.

**Comment by Mingu2209** [comment]
This is not working :( It requires a version of bookshelf and botany pots that I already have, so I bet that it's something that make no compatibility. Could you please double check?

**Comment by Darkhax** [comment]
This is confirmed fixed with 1.0.7
