### ISSUE TITLE
New Fiery Blossom Tree Quark

### ISSUE THREAD

**Issue by judicius** [Darkhax-Minecraft/BotanyTrees#20]
Quark added a tree that doesn't appear to be in the datapack. I have no idea how to create a pull request for red_blossom.json though, sorry.

`{
    "type": "botanypots:crop",
    "conditions": [
        {
            "type": "forge:mod_loaded",
            "modid": "quark"
        }
    ],
    "seed": {
        "item": "quark:red_blossom_sapling"
    },
    "categories": [
        "dirt"
    ],
    "growthTicks": 2400,
    "display": {
        "block": "quark:red_blossom_sapling"
    },
    "results": [
        {
            "chance": 0.50,
            "output": {
                "item": "minecraft:spruce_log"
            },
            "minRolls": 1,
            "maxRolls": 1
        },
        {
            "chance": 0.10,
            "output": {
                "item": "minecraft:stick"
            },
            "minRolls": 1,
            "maxRolls": 2
        },
        {
            "chance": 0.05,
            "output": {
                "item": "quark:red_blossom_sapling"
            },
            "minRolls": 1,
            "maxRolls": 1
        }
    ]
}`

**Comment by Darkhax** [comment]
Thanks for mentioning this. It's been added in the new update. https://github.com/Darkhax-Minecraft/BotanyTrees/commit/a9d4a3abd74c870229d0f6db097c8e3917f50d78
