### ISSUE TITLE
cant get wood from trees

### ISSUE THREAD

**Issue by iobiarg** [Darkhax-Minecraft/BotanyTrees#24]
Hi there, I love bot mods (pots and trees)
But when putting trees in the pots, they grow, but there is no way o getting wood out of them. By breaking the pot y get again the sapling. I don't know if I misunderstood the mod description or if sth is actually not working. 
Hugs

**Comment by iobiarg** [comment]
I realized that using the hopper pot i won't get anything by hand but if i put a container under i will, sorry for the inconvenience

**Comment by Darkhax** [comment]
For the normal pot you right click it after the tree has fully grown. You don't always get the drops, but it will restart the growth and you can try again.
