### ISSUE TITLE
Add Oh The Biomes You'll Go Trees & Pam's

### ISSUE THREAD

**Issue by MokahTGS** [Darkhax-Minecraft/BotanyTrees#3]
Please add compatibility for Oh The Biomes You'll Go and Pam's Fruit Trees.

**Comment by Darkfiend009** [comment]
I would love BYG compatibility! It's become a go to for biomes for me.

**Comment by Darkhax** [comment]
Pams isn't on 1.16 yet so it's a bit hard to add. BYG support was a lot of work but it should be on Curse soon. 

![image](https://user-images.githubusercontent.com/2250798/95417520-cc89fd00-0924-11eb-95e2-6f2f8403d99e.png)

**Comment by Darkhax** [comment]
BYG is now added and on Curse. I will add pam support when she has time to update. 

https://www.curseforge.com/minecraft/mc-mods/botany-trees/files/3074585

**Comment by MokahTGS** [comment]
Thanks!

**Comment by TheOldOne822** [comment]
Don't know if you know but pams has now updated to 1.16. With the world as crazy as it is ATM I wouldn't be supersized if you missed it or haven't had time to look into it yet if you were aware.
