### ISSUE TITLE
Support Pixelmon mod Apricorn trees

### ISSUE THREAD

**Issue by ceschiavolim** [Darkhax-Minecraft/BotanyTrees#38]
Could you add support for Apricorn trees from Pixelmon mod?

If you need I already have json files they just need to be balanced.

**Comment by Darkhax** [comment]
Hello, yes I would be interested in adding the Pixelmon apricorn trees. If you have the JSON files I would appreciate having them as a basis to work from.

**Comment by ceschiavolim** [comment]
Follow the Apricorn files.
[pixelmon.zip](https://github.com/Darkhax-Minecraft/BotanyTrees/files/9521882/pixelmon.zip)

**Comment by ceschiavolim** [comment]
An example:
`{
    "type": "botanypots:crop",
    "seed": {
        "item": "pixelmon:blue_apricorn"
    },
    "categories": [
        "dirt"
    ],
    "growthTicks": 2400,
    "display": {
        "block": "pixelmon:apricorn_plant_blue"
    },
    "results": [
        {
            "chance": 0.5,
            "output": {
                "item": "pixelmon:apricorn_log_blue"
            },
            "minRolls": 1,
            "maxRolls": 1
        },
        {
            "chance": 0.1,
            "output": {
                "item": "minecraft:stick"
            },
            "minRolls": 1,
            "maxRolls": 2
        },
        {
            "chance": 0.2,
            "output": {
                "item": "pixelmon:blue_apricorn"
            },
            "minRolls": 1,
            "maxRolls": 3
        },
        {
            "chance": 0.05,
            "output": {
                "item": "pixelmon:apricorn_leaves_blue"
            },
            "minRolls": 1,
            "maxRolls": 2
        }
    ]
}`

**Comment by ceschiavolim** [comment]
[apricorns.zip](https://github.com/Darkhax-Minecraft/BotanyTrees/files/9521907/apricorns.zip)

**Comment by ceschiavolim** [comment]
In the compressed file there are the seven variations.

**Comment by ceschiavolim** [comment]
I'm also planning to do **Berries** And **Mints** but I think it's better to put them in **BotanyPots**

**Comment by ceschiavolim** [comment]
I tried to make **mints**, but it's giving a strange error that I'm not able to identify

`{"type":"botanypots:crop","seed":{"item":"pixelmon:mint_seeds"},"categories":["dirt"],"growthTicks":2400,"display":{"block":"pixelmon:mint"},"results":[{"chance":0.01,"output":{"item":"pixelmon:mint_lonely"},"minRolls":1,"maxRolls":3},{"chance":0.01,"output":{"item":"pixelmon:mint_adamant "},"minRolls":1,"maxRolls":3},{"chance":0.01,"output":{"item":"pixelmon:mint_naughty "},"minRolls":1,"maxRolls":3},{"chance":0.01,"output":{"item":"pixelmon:mint_brave"},"minRolls":1,"maxRolls":3},{"chance":0.01,"output":{"item":"pixelmon:mint_bold"},"minRolls":1,"maxRolls":3},{"chance":0.01,"output":{"item":"pixelmon:mint_impish "},"minRolls":1,"maxRolls":3},{"chance":0.01,"output":{"item":"pixelmon:mint_lax "},"minRolls":1,"maxRolls":3},{"chance":0.01,"output":{"item":"pixelmon:mint_relaxed"},"minRolls":1,"maxRolls":3},{"chance":0.01,"output":{"item":"pixelmon:mint_modest "},"minRolls":1,"maxRolls":3},{"chance":0.01,"output":{"item":"pixelmon:mint_mild "},"minRolls":1,"maxRolls":3},{"chance":0.01,"output":{"item":"pixelmon:mint_rash  "},"minRolls":1,"maxRolls":3},{"chance":0.01,"output":{"item":"pixelmon:mint_quiet "},"minRolls":1,"maxRolls":3},{"chance":0.01,"output":{"item":"pixelmon:mint_calm "},"minRolls":1,"maxRolls":3},{"chance":0.01,"output":{"item":"pixelmon:mint_gentle "},"minRolls":1,"maxRolls":3},{"chance":0.01,"output":{"item":"pixelmon:mint_careful  "},"minRolls":1,"maxRolls":3},{"chance":0.01,"output":{"item":"pixelmon:mint_sassy "},"minRolls":1,"maxRolls":3},{"chance":0.01,"output":{"item":"pixelmon:mint_timid"},"minRolls":1,"maxRolls":3},{"chance":0.01,"output":{"item":"pixelmon:mint_hasty"},"minRolls":1,"maxRolls":3},{"chance":0.01,"output":{"item":"pixelmon:mint_jolly "},"minRolls":1,"maxRolls":3},{"chance":0.01,"output":{"item":"pixelmon:mint_naive "},"minRolls":1,"maxRolls":3},{"chance":0.01,"output":{"item":"pixelmon:mint_quirky"},"minRolls":1,"maxRolls":3},{"chance":0.01,"output":{"item":"pixelmon:mint_bashful"},"minRolls":1,"maxRolls":3},{"chance":0.01,"output":{"item":"pixelmon:mint_serious"},"minRolls":1,"maxRolls":3},{"chance":0.01,"output":{"item":"pixelmon:mint_docile"},"minRolls":1,"maxRolls":3},{"chance":0.01,"output":{"item":"pixelmon:mint_hardy"},"minRolls":1,"maxRolls":3}]}`

I don't know why the option list was so big, since the same plant has a chance to generate all types

**Comment by ceschiavolim** [comment]
As Berries are now also trees I am sending the Apricorns JSON files. hope this helps

[ApricornsAndBerries.zip](https://github.com/Darkhax-Minecraft/BotanyTrees/files/9522805/ApricornsAndBerries.zip)

**Comment by Darkhax** [comment]
Thanks for the help, I will look into cleaning these up and having them added soon.

**Comment by ceschiavolim** [comment]
Thank you very much for your attention and I look forward to it.

**Comment by Darkhax** [comment]
After looking into things more I felt that the pixelmon stuff would be better as it's own addon as they kind of blur the line between trees and normal crops. You can find that addon [here](https://www.curseforge.com/minecraft/mc-mods/botany-pots-pixelmon-compat). My version is currently missing logs/leaves/sticks from the drop table which is more in line with how similar edge case plants are handled, and the mint plant is also missing while I figure out the best way to balance it. Currently thinking a 10 or 15 minute growth time and then have a 5% chance for each of the mints to drop. Ideally it would just drop one mint but the system used in this older version is not flexible enough for drops like that.
