### ISSUE TITLE
[1.19.2 Forge] Biomes O' Plenty support does not work

### ISSUE THREAD

**Issue by EvergreenSystems** [Darkhax-Minecraft/BotanyTrees#39]
Botany Pots: 9.0.3
Botany Trees: 5.0.1
Biomes O Plenty: 17.1.1.150
Terrablender: 2.0.1.127

Forge: 43.1.32

As the title says, BotanyTrees does not support Biomes O' Plenty saplings in 1.19.2 forge despite what the curseforge description says. The pot won't accept the sapling.
![2022-10-08_11 52 58](https://user-images.githubusercontent.com/23658767/194718622-a8beb583-40c2-45a4-9988-3126792b3db1.png)

**Comment by Darkhax** [comment]
The 1.18/1.19 versions are still in alpha so mod support is not on par with the 1.16 versions yet.

**Comment by PhweeDev** [comment]
I'm assuming 1.18.2 and 1.19.2 will be updated later on when mod support is built in?

**Comment by Darkhax** [comment]
Yes, I will update for 1.18.2 and 1.19.2 when I have time. Hoping to focus on adding more mod support later this week.

**Comment by EvergreenSystems** [comment]
Cool! Awesome mod, appreciate the effort!

**Comment by PhweeDev** [comment]
Biomes o' Plenty support has been added for 1.18.2. 1.19.2 support on its' way.

**Comment by PhweeDev** [comment]
It has been added. Let me know if anything doesn't work!
