### ISSUE TITLE
Oh the Biome's You'll Go (Fruit Trees Data)

### ISSUE THREAD

**Issue by rowanthemodder** [Darkhax-Minecraft/BotanyTrees#4]
This is the data for the BYG fruit trees, only changes are adding the fruit the respective trees have.
[botanytreesbygfix.zip](https://github.com/Darkhax-Minecraft/BotanyTrees/files/5351793/botanytreesbygfix.zip)

**Comment by Darkhax** [comment]
Thanks this is now added.
