### ISSUE TITLE
1.19.2 BYG Support not working (Fabric)

### ISSUE THREAD

**Issue by GeniusLocEye** [Darkhax-Minecraft/BotanyTrees#40]
I was trying to use the BYG Ebony Sapling with a Botany Pot, but it doesn't seem to be working.

**Comment by Darkhax** [comment]
The 1.18/1.19 versions are still in alpha so mod support is not on par with the 1.16 versions yet. I will update for 1.18.2 and 1.19.2 when I have time. Hoping to focus on adding more mod support later this week.

**Comment by Darkhax** [comment]
These mods should now work fine. Please update to the latest version of botany trees and let me know if it still doesn't work.

- 1.18.2 was added in 4.0.4
- 1.19.2 was added in 5.0.3
