### ISSUE TITLE
Request support for: Ars Nouveau, Nature's Aura, EvilCraft, IntegratedDynamics (Forge 43.1.47)(Minecraft 1.19.2)

### ISSUE THREAD

**Issue by Devlah** [Darkhax-Minecraft/BotanyTrees#41]
Saplings from the title Mods will cycle once then stop at 100% when placed in a Hopper Botany Pot

**Comment by PhweeDev** [comment]
As of the latest 1.18.2 update, these have all been added. 1.19.2 is on its' way.

**Comment by Darkhax** [comment]
This should now be fixed. The modpack you are using will need to update and remove their unofficial support files.
