### ISSUE TITLE
Suggestion: Fix support for MyrTrees rubberwood trees

### ISSUE THREAD

**Issue by DerpyFrood0421** [Darkhax-Minecraft/BotanyTrees#45]
You can put the rubberwood sapling in the pot, and it grows to 100%, but is never harvested.  Yes, I'm using a hopper pot.
Not sure if this is an issue w/ MyrTrees itself or what but thought I would mention it as automating latex for FTB Contraptions would be much easier if this worked.

Minecraft version: 1.19.2
BotanyPots-Forge-1.19.2-9.0.13
BotanyTrees-Forge-1.19.2-5.0.1
myrtrees-forge-1.2.0-build.31
![image](https://user-images.githubusercontent.com/112346747/208145848-cdc74f2b-6d08-4ba4-87fc-9d64b430be5f.png)

**Comment by Darkhax** [comment]
This issue can happen in two different circumstances. 

1) There is nowhere for the drops to go. In your case the drawer may have an issue preventing the drops from going in. Please try with a chest instead and see if that helps.

2) The support for the tree is bugged and no valid drops were generated. I have not added support for this mod yet, and they have not added support on their end so I don't know who or where is adding it. It's possible the modpack themselves have independently added support.

**Comment by Darkhax** [comment]
Please just hold on and I will look into this more deeply.

**Comment by Darkhax** [comment]
The underlying issue of pots breaking when no loot is generated has been fixed in 9.0.16. The pack you are playing is still using unofficial support files but I have added the MyrTrees mod to my list.
