### ISSUE TITLE
Request: Support for Ars Nouveau

### ISSUE THREAD

**Issue by Jewlrose** [Darkhax-Minecraft/BotanyTrees#48]
I know you probably have a million things going on, but if it would be possible for you to add support to Ars Nouveau, or maybe just to add a text file where you can specify additional items to be plantable, that would be amazing.

**Comment by Darkhax** [comment]
Hello, Ars Nouveau should already be supported. Please update to the latest version of botany trees and let me know if it still doesn't work.

- 1.18.2 was added in 4.0.4
- 1.19.2 was added in 5.0.3
