### ISSUE TITLE
[Version Port] Polite request for 1.15?

### ISSUE THREAD

**Issue by xAlicatt** [Darkhax-Minecraft/BotanyTrees#5]
I understand maintaining multiple versions of a mod isn't always desired and if that's your plan, I understand. I just thought I would enquire if there will be a 1.15 version? I'm missing functionality in my 1.15 pack for OTBYG and some other mods with Bonsai Trees and having this instead would be the dream. Thank you for considering!

**Comment by Darkhax** [comment]
Added a 1.15.2 version. Support for mods is limited.
