### ISSUE TITLE
Croptopia fruit tree saplings / BYG trees 1.18.2

### ISSUE THREAD

**Issue by terafromm** [Darkhax-Minecraft/BotanyTrees#50]
Is there a way to make this work with the fruit trees? I saw Croptopia was on the list of compatibility, however I am not able to use any of the fruit trees. 

Edit: also BYG isn't working in 1.18.2 for me

**Comment by Darkhax** [comment]
Hello, which versions of the mods are you using? Both mods were recently added and should work fine.

**Comment by Darkhax** [comment]
After looking into it more, both mods should work fine. Please update to the latest version of botany trees and let me know if it still doesn't work.

- 1.18.2 was added in 4.0.4
- 1.19.2 was added in 5.0.3
