### ISSUE TITLE
doesn't seem to work with pam's harvest craft

### ISSUE THREAD

**Issue by drjkfseosilfsdkljsdogijdgjkd** [Darkhax-Minecraft/BotanyTrees#51]
When I plant Pam's harvest craft trees and feed it into my ME system, only the saplings will be harvested. not the fruit, sticks, or even the logs or leaves. I've no clue if its actually botanyTrees, but the Pam's harvest craft crops do work as they should, so...

**Comment by Darkhax** [comment]
Hello, pams trees appear to be working as intended on all versions. Fruits like the lemon tree have a 20% chance to drop their fruit on 1.19/1.18 and on 1.16.5 they had a 75% chance. You can confirm the drop pool by looking up the drops in JEI for the given seed item. If these items are not in the pool it is likely a 3rd party modification.
