### ISSUE TITLE
Request: Dynamic Trees compatibility

### ISSUE THREAD

**Issue by FrijDom** [Darkhax-Minecraft/BotanyTrees#53]
This is only a problem because they changed all the saplings into 'seeds' applicable to the trees (acorns, cones, etc.), but I'm honestly not sure if CraftTweaker is able to add recipes to this, so I'm asking for it as a sweeping addition.

**Comment by Darkhax** [comment]
Sorry this took so long, support has now been added. For 1.18.2 you need the 4.0.8 update, and on 1.19.2 you will need the 5.0.10 update. Both files are currently processing on CurseForge and should be available soon.
