### ISSUE TITLE
how can i change the growth speed of trees

### ISSUE THREAD

**Issue by InflaMe73** [Darkhax-Minecraft/BotanyTrees#54]
it hurts me that i cant change the growth speed in config. how can i do that on 1.16.5?

**Comment by Darkhax** [comment]
This mod uses datapacks to define the properties of the various crops. You can change a crop by creating a datapack that overrides the properties. You can read more [here](https://github.com/Darkhax-Minecraft/BotanyPots/wiki/Datapack-Information). If you're comfortable with CraftTweaker you can also write a script to do it, you can learn more about that [here](https://github.com/Darkhax-Minecraft/BotanyPots/wiki/CraftTweaker-Support).
