### ISSUE TITLE
BYG Holly Tree throwing errors

### ISSUE THREAD

**Issue by VaelophisNyx** [Darkhax-Minecraft/BotanyTrees#57]
`14.03 14:55:46 [Server] Server thread/[ERROR] Parsing error loading recipe botanytrees:byg/holly
14.03 14:55:46 [Server] [INFO] com.google.gson.JsonSyntaxException: Unknown item 'byg:holly_berries'
14.03 14:55:46 [Server] [INFO] at net.minecraft.class_1869.method_17878(class_1869.java:253) ~[server-intermediary.jar:?]
14.03 14:55:46 [Server] [INFO] at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
14.03 14:55:46 [Server] [INFO] at net.minecraft.class_1869.method_8155(class_1869.java:253) ~[server-intermediary.jar:?]
14.03 14:55:46 [Server] [INFO] at net.minecraft.class_1869.method_35228(class_1869.java:240) ~[server-intermediary.jar:?]
14.03 14:55:46 [Server] [INFO] at net.darkhax.bookshelf.api.serialization.SerializerItemStack.fromJSON(SerializerItemStack.java:27) ~[Bookshelf-Fabric-1.19.2-16.2.18.jar:?]
14.03 14:55:46 [Server] [INFO] at net.darkhax.bookshelf.api.serialization.SerializerItemStack.fromJSON(SerializerItemStack.java:14) ~[Bookshelf-Fabric-1.19.2-16.2.18.jar:?]
14.03 14:55:46 [Server] [INFO] at net.darkhax.bookshelf.api.serialization.ISerializer.fromJSON(ISerializer.java:51) ~[Bookshelf-Fabric-1.19.2-16.2.18.jar:?]
14.03 14:55:46 [Server] [INFO] at net.darkhax.botanypots.data.recipes.crop.SerializerHarvestEntry.fromJSON(SerializerHarvestEntry.java:23) ~[BotanyPots-Fabric-1.19.2-9.0.28.jar:?]
14.03 14:55:46 [Server] [INFO] at net.darkhax.botanypots.data.recipes.crop.SerializerHarvestEntry.fromJSON(SerializerHarvestEntry.java:13) ~[BotanyPots-Fabric-1.19.2-9.0.28.jar:?]
14.03 14:55:46 [Server] [INFO] at net.darkhax.bookshelf.api.serialization.ISerializer.fromJSONList(ISerializer.java:210) ~[Bookshelf-Fabric-1.19.2-16.2.18.jar:?]
14.03 14:55:46 [Server] [INFO] at net.darkhax.bookshelf.api.serialization.ISerializer.fromJSONList(ISerializer.java:232) ~[Bookshelf-Fabric-1.19.2-16.2.18.jar:?]
14.03 14:55:46 [Server] [INFO] at net.darkhax.botanypots.data.recipes.crop.BasicCropSerializer.fromJson(BasicCropSerializer.java:33) ~[BotanyPots-Fabric-1.19.2-9.0.28.jar:?]
14.03 14:55:46 [Server] [INFO] at net.darkhax.botanypots.data.recipes.crop.BasicCropSerializer.method_8121(BasicCropSerializer.java:17) ~[BotanyPots-Fabric-1.19.2-9.0.28.jar:?]
14.03 14:55:46 [Server] [INFO] at net.minecraft.class_1863.method_17720(class_1863.java:135) ~[server-intermediary.jar:?]
14.03 14:55:46 [Server] [INFO] at net.minecraft.class_1863.method_20705(class_1863.java:56) ~[server-intermediary.jar:?]
14.03 14:55:46 [Server] [INFO] at net.minecraft.class_1863.method_18788(class_1863.java:35) ~[server-intermediary.jar:?]
14.03 14:55:46 [Server] [INFO] at net.minecraft.class_4080.method_18790(class_4080.java:13) ~[server-intermediary.jar:?]
14.03 14:55:46 [Server] [INFO] at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
14.03 14:55:46 [Server] [INFO] at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
14.03 14:55:46 [Server] [INFO] at net.minecraft.class_4014.method_18365(class_4014.java:69) ~[server-intermediary.jar:?]
14.03 14:55:46 [Server] [INFO] at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
14.03 14:55:46 [Server] [INFO] at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
14.03 14:55:46 [Server] [INFO] at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
14.03 14:55:46 [Server] [INFO] at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[server-intermediary.jar:?]
14.03 14:55:46 [Server] [INFO] at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[server-intermediary.jar:?]
14.03 14:55:46 [Server] [INFO] at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
14.03 14:55:46 [Server] [INFO] at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[server-intermediary.jar:?]
14.03 14:55:46 [Server] [INFO] at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[server-intermediary.jar:?]
14.03 14:55:46 [Server] [INFO] at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[server-intermediary.jar:?]
14.03 14:55:46 [Server] [INFO] at net.minecraft.server.MinecraftServer.method_29439(MinecraftServer.java:1316) ~[server-intermediary.jar:?]
14.03 14:55:46 [Server] [INFO] at net.minecraft.class_3097.method_29480(class_3097.java:22) ~[server-intermediary.jar:?]
14.03 14:55:46 [Server] [INFO] at de.rubixdev.rug.RugServer.reload(RugServer.java:412) ~[rug-1.19.1-1.3.7.jar:?]
14.03 14:55:46 [Server] [INFO] at de.rubixdev.rug.RugServer.onServerLoadedWorlds(RugServer.java:249) ~[rug-1.19.1-1.3.7.jar:?]
14.03 14:55:46 [Server] [INFO] at carpet.CarpetServer.lambda$onServerLoadedWorlds$3(CarpetServer.java:108) ~[fabric-carpet-1.19.2-1.4.84+v221018.jar:?]
14.03 14:55:46 [Server] [INFO] at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
14.03 14:55:46 [Server] [INFO] at carpet.CarpetServer.onServerLoadedWorlds(CarpetServer.java:108) ~[fabric-carpet-1.19.2-1.4.84+v221018.jar:?]
14.03 14:55:46 [Server] [INFO] at net.minecraft.server.MinecraftServer.handler$bjm000$carpet$serverLoadedWorlds(MinecraftServer.java:6292) ~[server-intermediary.jar:?]
14.03 14:55:46 [Server] [INFO] at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:330) ~[server-intermediary.jar:?]
14.03 14:55:46 [Server] [INFO] at net.minecraft.class_3176.method_3823(class_3176.java:172) ~[server-intermediary.jar:?]
14.03 14:55:46 [Server] [INFO] at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:636) ~[server-intermediary.jar:?]
14.03 14:55:46 [Server] [INFO] at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
14.03 14:55:46 [Server] [INFO] at java.lang.Thread.run(Thread.java:831) [?:?]`

**Comment by VaelophisNyx** [comment]
they also cannot be put into a botany pot

**Comment by Darkhax** [comment]
Thanks for letting me know about this issue. A new build will be out soon with the fix.

https://www.curseforge.com/minecraft/mc-mods/botany-trees/files/4457946
