### ISSUE TITLE
Not showing Simple Farming trees as pot crops in JEI...

### ISSUE THREAD

**Issue by whiteeagle1985** [Darkhax-Minecraft/BotanyTrees#58]
I don't know if it's your mod or JEI, but Simple Farming trees don't show up as a crop in Botany Pots (and I have Trees installed as well). I'm using 1.19.2 and the latest versions of JEI, Simple Farming, Botany Pots, and Botany Trees. 

I tend to use JEI to check and see what recipes work, so I don't waste resources and craft something which won't work. If the trees work in the Botany Pots, it would stand to see that they would show up like that in JEI.

**Comment by Darkhax** [comment]
Thanks for letting me know. Looks like they changed some block IDs. This should now be fixed in 5.0.8 on CurseForge.
