### ISSUE TITLE
Flashing Archwood Sapling from Ars Elemental cannot be grown

### ISSUE THREAD

**Issue by PonyWarrior** [Darkhax-Minecraft/BotanyTrees#59]
The Flashing Archwood Sapling from Ars Elemental cannot be grown in a botany pot while the other saplings from Ars Nouveau can (Vexing/Blazing/Cascading/Flourishing)

![image](https://user-images.githubusercontent.com/22421356/236649191-7a61168d-eadf-4883-bb51-5c25ba88d3d2.png)
![image](https://user-images.githubusercontent.com/22421356/236649197-e6dd26f7-6f42-46a9-be8a-5b35a6f5fef2.png)
![image](https://user-images.githubusercontent.com/22421356/236649202-907d0691-de87-4b27-9d7c-d471df8fd9ab.png)
![image](https://user-images.githubusercontent.com/22421356/236649394-7aa9fa5b-70d4-458d-894e-9a83ae60ce0c.png)
![image](https://user-images.githubusercontent.com/22421356/236649208-d485a3f1-7271-44cc-8f3e-f2e164890da3.png)

BotanyPots version : 9.0.31
BotanyTrees version : 5.0.4

Ars Nouveau version : 3.13.2
Ars Elemental version : 1.19.2-0.5.8.2

Minecraft version : 1.19.2
Modpack : All the mods 8
Modpack version : 1.0.17

**Comment by Darkhax** [comment]
Thanks for letting me know. This should now be fixed in 5.0.8 on CurseForge.
