### ISSUE TITLE
Config Speed of tree growth

### ISSUE THREAD

**Issue by MokahTGS** [Darkhax-Minecraft/BotanyTrees#6]
Is there a way to speed up or slow down tree growth?  Currently tree growth is way slower than Bonsai Pots.

**Comment by Darkhax** [comment]
The slow growth is intentional. The entire mod is json-defined config files, you just need to find the one you want to change.

**Comment by MokahTGS** [comment]
Sorry, I couldn't find them.  Where are they located?

**Comment by Darkhax** [comment]
They are inside the JAR file. You can also use datapacks for a more modpack friendly approach.

**Comment by MokahTGS** [comment]
Ok thanks

**Comment by MokahTGS** [comment]
Can I have a bit of guidance on growth ticks?  The default for an oak is 2400 under growth ticks.  Is that 2400 ticks for one growth tick or is that 2400 ticks for a fully grown sapling?

**Comment by Darkhax** [comment]
This depends on the version of the mod you're playing. 

[1.15+](https://github.com/Darkhax-Minecraft/BotanyPots/wiki/Technical-Info)
[1.14.4](https://gist.github.com/Darkhax/88363abb97ed27d6f003b6da060eb5b2)

**Comment by Darkhax** [comment]
I forgot this mod is only for 1.16+, my bad. So in this version the growth ticks is how long it takes for the crop to grow on normal soil. 2400 = 120 seconds. If you lower the number to 1200 it will be speed it up to 1 minute which is twice as fast.

**Comment by MokahTGS** [comment]
Great thx

**Comment by InflaMe73** [comment]
> Great thx
did you find where is config located?
