### ISSUE TITLE
Request for support for Terrestria trees

### ISSUE THREAD

**Issue by jjslocum3** [Darkhax-Minecraft/BotanyTrees#60]
Hi, wondering if you'd add some recipes for the terrestria trees? 

* terrestria:rubber_sapling 
* terrestria:rubber_log
* terrestria:hemlock_sapling
* terrestria_hemlock_log

**Comment by Darkhax** [comment]
Thanks for the suggestion. The terrestria mod has been supported in https://github.com/Darkhax-Minecraft/BotanyTrees/commit/e58647efd202979b9967a2dd4777850fde99c1d1 and is available as 7.0.4 on CurseForge.
