### ISSUE TITLE
Request: Tech Reborn

### ISSUE THREAD

**Issue by ElegaicRequiem** [Darkhax-Minecraft/BotanyTrees#61]
Could compatibility with the rubber saplings be added to this? Thank you.

**Comment by Darkhax** [comment]
Sorry for taking so long to reply to this. Tech Reborn rubber trees should be supported now.

- 1.18.2 should use 4.0.10+
- 1.19.2 should use 5.0.11+
- 1.19.4 should use 7.0.6+
- 1.20.1 should use 9.0.2+
