### ISSUE TITLE
compatibility for dynamic trees?

### ISSUE THREAD

**Issue by SonicTheHedgehog58987276** [Darkhax-Minecraft/BotanyTrees#64]
i haven't used this mod yet, but i'm just downloading it at the time of posting this issue, but can you add a way to use dynamic trees mod along with?

**Comment by SonicTheHedgehog58987276** [comment]
1.16.5 compatibility for now?

**Comment by Darkhax** [comment]
This feature has now been backported. The file is being processed by CurseForge and will be available on the project page once it's available.
