### ISSUE TITLE
Tconstruct earth slime sapling recipe error on 1.16

### ISSUE THREAD

**Issue by MundM2007** [Darkhax-Minecraft/BotanyTrees#68]
the error is simply that the "drops" section is named "results" in 1.16 this hasn't been adjusted in the version.
This is really annoying as it causes an error with kubejs for some reason.

**Comment by Darkhax** [comment]
Thanks, this should be fixed in [3.0.12](https://www.curseforge.com/minecraft/mc-mods/botany-trees/files/4788558)
