### ISSUE TITLE
Fruit trees - Emphasis Fruit

### ISSUE THREAD

**Issue by ClaudiusMinimus** [Darkhax-Minecraft/BotanyTrees#7]
I'm testing Botany trees for my 1.16.3 pack and found the Simple Farming fruit trees seem to emphasize wood and not fruit. It would seem if a player put a fruit tree in a botany pot, then they would expect fruit.

Thanks, CM

BTW: I really love your botany pots and other mods! Keep up the great work!

**Comment by Warbringer12** [comment]
if you wanted to have it emphasize fruit for your pack you could just do a simple data pack json to fix that.

**Comment by Darkhax** [comment]
While prioritizing the fruit would make more logical sense I decided to make it prioritize the wood to keep it consistent with vanilla. Making the fruit spawn more could make rare items too common. Feel free to tweak things how you would like using CraftTweaker or data packs though.
