### ISSUE TITLE
Added support to output leaves.

### ISSUE THREAD

**Issue by Nightfall301** [Darkhax-Minecraft/BotanyTrees#72]
Would it be possible to add the respective leaves to the output tables for the trees?
It was a feature on the Bonsai Trees mod, and could be useful for hardcore decorators or folks looking for more fodder for their composters.
Thank you.

**Comment by Darkhax** [comment]
Hello, this was removed from earlier versions of the mod because many players complained about leave items being spam. This mod pulls its data entirely from the datapack system so they can be added back with a datapack or with tools like CraftTweaker.
