### ISSUE TITLE
BOP orange autumn sapling drop

### ISSUE THREAD

**Issue by nanalich456** [Darkhax-Minecraft/BotanyTrees#76]
Just a note that the orange autumn sapling from Biomes O Plenty should drop dark oak logs instead of oak logs. Thanks for your time!

**Comment by Darkhax** [comment]
Thanks for letting me know, and sorry for taking so long to get around to this. This should now be fixed for 1.18.2, 1.19.2, 1.19.4, 1.20.1, and 1.20.4.
