### ISSUE TITLE
[BUG]  Incorrect Compact Item Name for Vampirism 

### ISSUE THREAD

**Issue by KakashoLin** [Darkhax-Minecraft/BotanyTrees#78]
### Minecraft Version

1.20.1

### Mod Version

BotanyTrees-Forge-1.20.1-9.0.9

### Mod Loader

Forge

### What environment are you running the mod in?

All

### Issue Description

First noticed it on my server but also affects singleplayer.

The naming scheme for both trees from Vampirism is pointing to an incorrect, possibly a older name for both trees?

**Old**                                              >             **New**
vampirism:bloody_spruce_sapling    > vampirism:cursed_spruce_sapling
vampirism:bloody_spruce_log > vampirism:cursed_spruce_log
vampirism:vampire_spruce_log > vampirism:dark_spruce_log
vampirism:vampire_spruce_sapling > vampirism:dark_spruce_log

Also here is the name scheme for the dirt and grass they grow on if that helps!
vampirism:cursed_grass
vampirism:cursed_earth

Attached are the two json files that have the incorrect name.

[vampire_spruce.json](https://github.com/Darkhax-Minecraft/BotanyTrees/files/14289044/vampire_spruce.json)
[bloody_spruce.json](https://github.com/Darkhax-Minecraft/BotanyTrees/files/14289046/bloody_spruce.json)

**Comment by Darkhax** [comment]
Thanks for letting me know about this. I've updated to mod to account for these changes. Updating to BotanyPots 13.0.24 and BotanyTrees 9.0.11 should work.
