### ISSUE TITLE
[1.16.3]crafttweaker support does not cover this addon

### ISSUE THREAD

**Issue by raziel23x** [Darkhax-Minecraft/BotanyTrees#8]
Minecraft: 1.16.3
Forge: 34.1.42
BotanyPots-1.16.3-5.1.9
BotanyTrees-1.16.3-1.0.7
CraftTweaker-1.16.3-7.0.0.48

i tried using the wheat example to modifiy the drops for the vanilla trees
https://github.com/Darkhax-Minecraft/BotanyPots/wiki/CraftTweaker-Support

Here are the two different ways i tried the script unsuccessful with getting the ZS to work
https://gist.github.com/raziel23x/1f45d535698aa4c14a7b9b3f260e1e45

but when i load the mod in minecraft and here is the crafttweaker log 
https://gist.github.com/raziel23x/cc9f137706ed6555fc39d18a12a567e5

**Comment by Warbringer12** [comment]
usually for 1.16.3 you have to write them as .json and its not a crop or anything so look at how he has it laid out in his code to see how he did it and usually you can modify the drops very easily for them

**Comment by raziel23x** [comment]
according to the wiki in the link above in his own wiki in the botany crop mod that this is a addon for you do it this way if you are using crafttweaker. I Am able to modify it in a datapack just fine but the craft tweaker support this is suppose to have as well is not working as intended

**Comment by Darkhax** [comment]
This is caused by misunderstanding the documentation and using the wrong ids.
